services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      HOST: 0.0.0.0
      PORT: 4000

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  demo-http:
    build:
      context: .
      dockerfile: demo/http/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DEBUGVIZ_ENABLED: "true"
      DEBUGVIZ_SERVER_URL: http://server:4000
      DEBUGVIZ_SERVICE_NAME: demo-http
    depends_on:
      - server
