package main

// Codegen entry points for demo/http (M3 + M6).
//
//go:generate go run ../../go/cmd/debugviz wire --config ../../debugviz.yaml --write ./...
//go:generate go run ../../go/cmd/debugviz instrument --config ../../debugviz.yaml --write ./internal/service/... ./internal/repository/...
